services:
  mariadb:
    image: mariadb:noble
    container_name: tinygopher_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: lsignore
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: tinygopher
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql"
